server:
  port: 9060


spring:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/security-demo?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Seoul
    username: jongwon
    password: "whddnjs121!"

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    check-template-location: true
    suffix: .html

#  web:
#    resources:
#      static-locations:

logging:
  level:
    org.springframework.web: trace
